on:
  workflow_call:
    inputs:
      benchmarks:
        description: "paths to benchmarks, comma seperated"
        type: string
        required: true

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    if: ${{ github.event.inputs.benchmarks == '' }}
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(inputs.benchmarks) }}
  
    env:
      cache: true
      ARTIFACTS_FOLDER: artifacts

    defaults:
      run:
        shell: bash
        working-directory: benchmarks/${{ matrix.path }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - uses: actions/cache@v3
        if: env.cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/home/linuxbrew/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock', 'run.sh') }}

      - run: mkdir -p ${{ env.ARTIFACTS_FOLDER }}
      - name: Make executable
        run: |
          # run.sh might not be executable
          chmod +x run.sh

      - name: Run benchmark
        run: ./run.sh

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: artifacts-${{ matrix.path }}
      #     path: benchmarks/${{ matrix.path }}/${{ env.ARTIFACTS_FOLDER }}
